# Generated by Django 4.1.3 on 2022-11-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("1", "Done"), ("2", "Not done")], default="2", max_length=255
            ),
        ),
    ]
